name = "mybcs"
compatibility_date = "2024-01-01"
pages_build_output_dir = "./dist"
[assets]
directory = "./dist"
[[d1_databases]]
binding = "DB"
database_name = "bcs-study-db"
database_id = "88003a0b-a13f-47a4-8ab5-2c168e2bf12c"
